### ISSUE TITLE
Backward compatible with Python2.7

### ISSUE THREAD

**Issue by Git-droid** [akesterson/dpath-python#121]
Hi, I am not able to use dpath.util.get in Python2.7.
"""
from collections.abc import MutableMapping
from collections.abc import MutableSequence
"""
in Python2.7 this is not available.
I did a little workaround:
"""
try:
    from collections.abc import MutableMapping
except ImportError:
    from collections import MutableMapping
try:
    from collections.abc import MutableSequence
except ImportError:
    from collections import MutableSequence
"""

Will Python2.7 support included in future? Or can this little trick be part of the official release. No other functions tested, only dpath.util.get!

Thanks in advance!

**Comment by ihadgraft** [comment]
@Git-droid Python2 is end-of-life as of 1/1/2020, and there can no longer be any expectation of support for it. See https://www.python.org/doc/sunset-python-2.

**Comment by calebcase** [comment]
The 1.x series was the last to support python 2.7. Since python 2 is EOL we won't be supporting it in the 2.x and future versions.
