### ISSUE TITLE
Exception not thrown when glob don't exist

### ISSUE THREAD

**Issue by vagarwal77** [akesterson/dpath-python#133]
Love this library...working like a charm :) 
Need suggest on below what i can do to catch if glob (or xpath or key) don't exist within nested dictionary. If it exist than it is able to set the values successfully. 
Please suggest!!!

No exception thrown when map_path_att path don't exist in the nested json
try:                
      dpath.util.set( load_res,map_path_att, dict_variable[field] )
except Exception as err:
        print(err)

**Comment by akesterson** [comment]
This is working as designed, though we admit the v1 API isn't clear on this point. set() is used to both set existing keys, and also to create new objects within a dictionary. So when a glob does not exist, it will silently create it and succeed.
