### ISSUE TITLE
Searching for multiple keys only works with single character keys

### ISSUE THREAD

**Issue by dnikoliouk** [akesterson/dpath-python#135]
```
x = {
    "a": {
        "b": {
        "3": 2,
        "43": 30,
        "c": [],
        "d": ['red', 'buggy', 'bumpers'],
        }
    }
}

>>> dpath.util.search(x, "a/b/[43d]")
>>> {'a': {'b': {'3': 2}}}
```

In this example I'm trying get values for key **43** and key  **d**, but only value for the key **3** is returned. Is this by design or am I doing something wrong? Please advise. Thank you.

**Comment by akesterson** [comment]
This is working as designed. Using [...] to match a range will match any single character from the range. So you will match keys named 3, 4, OR d, but not 43. Make sense?
