### ISSUE TITLE
New Maintainers Wanted : Existing Maintainers Are Abandoning

### ISSUE THREAD

**Issue by akesterson** [akesterson/dpath-python#136]
Hey there community. @calebcase and I are thrilled that dpath was, and still is, so well received by the python community. We have been excited to engage all of you on your issues and feature requests. However, as time has gone by, we have been challenged to continue maintaining the project. We do not use it professionally anymore, and we have a hard time syncing our schedules to perform regular maintenance tasks on the library. Even getting releases out the door has become cumbersome. You, our community, deserve more responsive maintainers.

We are looking to hand this project off to a new maintainer. Henceforth, we will issue NO FURTHER BUILDS for any reason. At this time 1.x is stable and free of major bugs; 2.x is stable and shows the way forward; and 3.x has some issues written up for future development. Anyone who wants to submit a bugfix or feature is encouraged to fork the project.

We still maintain ownership of the python pypi package and the automated build in Travis. Any individual who wants to continue publishing dpath updates under the existing project name can reach out to us to be added as a collaborator on the python project page and on the travis builds. Eventually, those will be handed over completely to whomever can prove themselves a good maintainer. You are also free to fork it, rename it, and publish new packages to pypi using the new name. If you do so, please let us know, and we WILL update the pypi documentation and the github documentation to point to  your fork.

We will close this issue when a new maintainer has stepped up.

**Comment by dargueta** [comment]
I'm willing to contribute time to this.

**Comment by akesterson** [comment]
@bigsablept and @moomoohk have stepped up to begin maintaining this project. Self and @calebcase  to cover the above-referenced PRs to indicate that this project has new maintainers.
