### ISSUE TITLE
Attempting to use dpath for this output

### ISSUE THREAD

**Issue by singlecheeze** [akesterson/dpath-python#44]
How would I use dpath, or is it even possible, to get this output given this list:
```
B-A.txt
B-B.txt
B-C
B-C/B-C-A.txt
B-C/B-C-B.txt
B-C/B-C-C
B-C/B-C-C/B-C-C-B.txt
B-C/B-C-C/B-C-C-A.txt
```
Output:
```
{
   "fullpath": "uploads_fortest/v999999/B.tar.gz",
   "name": "B.tar.gz",
   "paths": [
      {
         "fullpath": "uploads_fortest/v999999/B.tar.gz/B-A.txt",
         "name": "B-A.txt",
         "type": "file"
      },
      {
         "fullpath": "uploads_fortest/v999999/B.tar.gz/B-B.txt",
         "name": "B-B.txt",
         "type": "file"
      },
      {
         "fullpath": "uploads_fortest/v999999/B.tar.gz/B-C",
         "name": "B-C",
         "paths": [
            {
               "fullpath": "uploads_fortest/v999999/B.tar.gz/B-C/B-C-A.txt",
               "name": "B-C-A.txt",
               "type": "file"
            },
            {
               "fullpath": "uploads_fortest/v999999/B.tar.gz/B-C/B-C-B.txt",
               "name": "B-C-B.txt",
               "type": "file"
            },
            {
               "fullpath": "uploads_fortest/v999999/B.tar.gz/B-C/B-C-C",
               "name": "B-C-C",
               "paths": [
                  {
                     "fullpath": "uploads_fortest/v999999/B.tar.gz/B-C/B-C-C/B-C-C-B.txt",
                     "name": "B-C-C-B.txt",
                     "type": "file"
                  },
                  {
                     "fullpath": "uploads_fortest/v999999/B.tar.gz/B-C/B-C-C/B-C-C-A.txt",
                     "name": "B-C-C-A.txt",
                     "type": "file"
                  }
               ],
               "type": "file"
            }
         ],
         "type": "file"
      }
   ],
   "type": "tarfile"
}
```
What I am trying to do is iterate over the output of tarfile.getmembers() and build a json tree without having to recurse using your dpath.

So far my recursion kinda works (not really as I can't set "type" appropriately)...
```python
def add(branch, trunk):
        parts = branch.split('/', 1)
        if "paths" not in trunk:
            trunk["paths"] = []

        if len(parts) > 1:
            node, others = parts
            # print(trunk["paths"][-1])
            add(others, trunk["paths"][-1])

        elif len(parts) == 1:
            # trunk["type"] = file_type
            trunk["paths"].append(dict(fullpath=os.path.join(trunk["fullpath"], parts[0]),
                                       name=os.path.basename(parts[0]),
                                       type="file"))

result = {"fullpath": tar_path, "name": os.path.basename(tar_path), "type": "tarfile"}
tar = tarfile.open(tar_path)
tar_infos = tar.getmembers()
for member in tar_infos:
      add(member.name, result)
``` 

This is the contents of a tar file therefore I can't use os.listdir and the like. Also I'd like to be able to create the master json recursively for any tar files found inside a tarfile with a wrapper function.

Any good ideas ;) ?

**Comment by akesterson** [comment]
Just to be clear, this isn't a dpath question, this is a recursion question.

I don't think there's an elegant solution to this, given your data format, without using recursion. Can you change your data format? If you could, then this solution becomes fairly trivial with dpath without recursion.

    >>> output = {"fullpath": "uploads_fortest/v999999/B.tar.gz", "name": "B.tar.gz", "paths": {}}
    >>> for line in input:
    ...     if line.endswith(".txt"):
    ...             dpath.util.new(output['paths'], line, {"type": "file", "name": os.path.basename(line)})
    ...     else:
    ...             dpath.util.new(output['paths'], line, {})
    ... 
    >>> print json.dumps(output, indent=4, sort_keys=True)
    {
        "fullpath": "uploads_fortest/v999999/B.tar.gz", 
        "name": "B.tar.gz", 
        "paths": {
            "B-A.txt": {
                "name": "B-A.txt", 
                "type": "file"
            }, 
            "B-B.txt": {
                "name": "B-B.txt", 
                "type": "file"
            }, 
            "B-C": {
                "B-C-A.txt": {
                    "name": "B-C-A.txt", 
                    "type": "file"
                }, 
                "B-C-B.txt": {
                    "name": "B-C-B.txt", 
                    "type": "file"
                }, 
                "B-C-C": {
                    "B-C-C-A.txt": {
                        "name": "B-C-C-A.txt", 
                        "type": "file"
                    }, 
                    "B-C-C-B.txt": {
                        "name": "B-C-C-B.txt", 
                        "type": "file"
                    }
                }
            }
        },
        "type": "tarfile"
    }

But this datastructure probably could be changed to something less generic and more suited to its actual purpose.

    >>> x = Tarball(filename)
    >>> x.tarballs
    # ... returns a list of child tarballs found inside the archive as Tarball objects ...
    >>> x.files
    # ... returns a list of all files inside the archive (including the names of all the objects described in x.tarballs ...

But that's just my $.02

**Comment by singlecheeze** [comment]
Thanks Andrew, you are right this is more of a recursion question. Changing
dataset is not possible as this is delivered to a telerik jQuery control on
a web front end and they need a pretty generic data format in order to
build a treeview.

On a seperate note, what is the x = Tarball(filename) reference you make?
Is that from stdlib?


On Sun, Oct 11, 2015 at 11:27 AM, Andrew Kesterson <notifications@github.com

**Comment by akesterson** [comment]
> On a seperate note, what is the x = Tarball(filename) reference you make?

I was just saying I'd stop trying to do this 100% inside of a dictionary, and instead make a class Tarball that could hold the list of file members, and the list of sub-tarballs in a separate member. But it sounds like your use case makes it more practical to do it all in a dictionary.

Either way this dataset and this problem set seem made for recursion. Why are you avoiding it? There would have to be a *ton* of nested tarballs to hit the recursion limit.

**Comment by singlecheeze** [comment]
Avoiding it.... because it costs brain cells lol. Nah I ended up doing recursion to solve the issue but would have much rather used dpath :+1: 

I use a lot of telerik in my projects and they require homogeneous data sets that do not allow for rendering true nested & contextual dictionaries like your dpath uses. Of course this makes for a lot of bytes sent from back end to front end that are a waste, but I guess it would be pretty impossible to render a control like a tree view without generic fields.
