### ISSUE TITLE
Query for "entire structure?"

### ISSUE THREAD

**Issue by remleduff** [akesterson/dpath-python#46]
I assumed that there would be a way to return the entire dictionary somehow, but I can't seem to find one. Would it be useful?

ie:

x = {1:"first", 2:"second"}

dpath.util.get(x, "/") => return entire dictionary

**Comment by akesterson** [comment]
Search with ** will match everything at all levels, returning the entire dictionary.

    >>> import dpath.util
    >>> x = {1:"first", 2:"second"}
    >>> dpath.util.search(x, "**")
    {1: 'first', 2: 'second'}

**Comment by remleduff** [comment]
I see. Let me explain a little bit more what my thinking was.

I'd like to expose an API to consumers (currently over zerorpc).

```python
import dpath

class Central:
     state = {}

     def get(self, path):
         return dpath.get(state, path)

    def set(self, path, value):
        return dpath.new(state, path, value)
```

This allows my consumers to query for exactly the piece of state that they would like.

However, it would be convenient if they could somehow query for "everything" using the same API. Thanks to your answer, I can handle that myself now, but it's a discontinuity in the dpath API that doesn't seem necessary at first glance.

**Comment by akesterson** [comment]
It's not a discontinuity in the API, both methods work as they are documented. (One gets a specific value, another searches for key/value pairs at arbitrary levels of the dictionary.)

If all you want to do is return the entire dictionary, you don't even need dpath for that, just return the user the dictionary, and be done?

If you are trying to say that you want your users to be able to query all VALUES in the dictionary, as opposed to returning "everything" - which I am interpreting to mean "the entire dictionary" - then you can use dpath.util.values for that, which will return all the values for all the keys matching the search path:

    >>> import dpath.util
    >>> x = {1: 'first', 2: 'second'}
    >>> dpath.util.values(x, '**')
    ['first', 'second']

... but the results of this will become confusing as you path infinitely into multi-level dictionaries:

    >>> x = {1: 'first', 2: 'second', 3: {'a': 0, 'b': 2, 'c': [0, 1, 2]}}
    >>> dpath.util.values(x, '**')
    ['first', 'second', {'a': 0, 'c': [0, 1, 2], 'b': 2}, 0, [0, 1, 2], 0, 1, 2, 2]

... But I'm not entirely sure that's what you're after either.
