### ISSUE TITLE
Posible to merge lists uniqe

### ISSUE THREAD

**Issue by demwz** [akesterson/dpath-python#53]
is it possible to add a something like  MERGE_UNIQUE so 2 lists are combined to a single list of unique values

merge(    ['1','3','4',5']    ,     ['1','2','3']     )
['1','2','3','4',5']

Would be great -  thanks

**Comment by calebcase** [comment]
Discussed with @akesterson and it feels out of scope. As @hallabalooza has demonstrated you can realize this by doing the get and then converting it to a set.
