### ISSUE TITLE
get root of dictionary

### ISSUE THREAD

**Issue by hallabalooza** [akesterson/dpath-python#54]
Hi.

It is possible to get leafs of a dictionary e.g. x = {'p':{'a':{'t':{'h':'value'}}, 'f':'misc'} with dpath by e.g.
dpath.util.get(x, "/p/a/t/h").
But how to get the root? I expected something like dpath.util.get(x, "/") returns "x". But this does not work currently.

Thnks,
H.

**Comment by jackmaney** [comment]
`x` is the name of the variable assigned to the dictionary, not a key or value therein. Try `x.__name__`.

**Comment by calebcase** [comment]
Working in 2.0
