### ISSUE TITLE
Fatal error with empty keys

### ISSUE THREAD

**Issue by lakadbaggha** [akesterson/dpath-python#55]
Even if you set `dpath.options.ALLOW_EMPTY_STRING_KEYS = True`, and `dpath.util.search` on a dict with empty keys, you will hit a IndexError exception thanks to `elif (skip and k[0] == '+'):` in `dpath.path.paths`

**Comment by akesterson** [comment]
What version of dpath are you using?

**Comment by lakadbaggha** [comment]
1.4

**Comment by shellshock1953** [comment]
1.4.2 - same here, unable to use `""` as dict key, even if `dpath.options.ALLOW_EMPTY_STRING_KEYS = True`

**Comment by calebcase** [comment]
Works in 2.0

**Comment by calebcase** [comment]
Fixed in 2.x and 2.x is now released. Please upgrade and let us know how it goes. Thanks for the report!
