### ISSUE TITLE
Cannot merge at various levels

### ISSUE THREAD

**Issue by mcaulifn** [akesterson/dpath-python#57]
I am attempting to search a dictionary for a key, retrieve the value, pop the key, and insert the contents of a file in its place.
Given dictionary:
`
{
  'z': ['1.1.1.1', '1.1.1.2'], 
  'include': 'file1.json', 
  'u': 
    {'include': 'file2.json'}, 
  'hello': 'goodbye'}
`
Is it possible to merge at multiple levels without having the source files match the levels of the destination dictionary?

**Comment by calebcase** [comment]
It is not possible to merge at multiple levels without the source files matching. However you should be able to achieve what you are looking for (in 2.0) with something like:

```
x = { 'z': ['1.1.1.1', '1.1.1.2'], 'include': 'file1.json', 'u': {'include': 'file2.json'}, 'hello': 'goodbye'}
t = list(dpath.util.search(x, '**/include', yielded=True))
for (p, n) in t:
   data = {'some': 'data from a file'}
   dpath.util.set(x, p, data)
print(x)
```

Which should result in all `include` keys being replaced with `data`.
