### ISSUE TITLE
Asterix search does not appear to work

### ISSUE THREAD

**Issue by tmiseur** [akesterson/dpath-python#60]
I noticed that the example in the readme doesn't actually work:

```
import dpath.util
import json

x = {
    "a": {
        "b": {
        "3": 2,
        "43": 30,
        "c": [],
        "d": ['red', 'buggy', 'bumpers'],
        }
    }
}

print(str(dpath.util.values(x, '/a/b/d/\*')))
>>> []
```

The documentation suggests it should return this:
`['red', 'buggy', 'bumpers']`

**Comment by tmiseur** [comment]
It works without the forward-slash though, so it's probably just a typo in the readme.

**Comment by akesterson** [comment]
Thank you, this was a typo in the README. We have fixed the document.
