### ISSUE TITLE
feature request - anchor & collapse path

### ISSUE THREAD

**Issue by ipmonk** [akesterson/dpath-python#61]
I've used perls Data::Dpath (https://metacpan.org/pod/Data::DPath) in the past and found its 'special elements' feature really useful (pasted below). Would it be possible to implement the same functionality?

//
Anchors to any hash or array inside the data structure below the currently found points (or the root).

Typically used at the start of a path to anchor the path anywhere instead of only the root node:

//FOO/BAR
but can also happen inside paths to skip middle parts:

/AAA/BBB//FARAWAY
This allows any way between BBB and FARAWAY.

*  << this bullet is supposed to be an asterisk

Matches one step of any value relative to the current points (or the root). This step might be any hash key or all values of an array in the step before.

**Comment by akesterson** [comment]
You want star-star globbing.

`**/FOO/BAR matches all elements of FOO/BAR at an arbitrary depth of the object being searched
/AAA/BBB/**/FARAWAY matches all elements of FARAWAY at any arbitrary depth of the object being searched BENEATH /AAA/BBB
** as a path by itself will match all possible paths in the object`
