### ISSUE TITLE
MERGE_REPLACE does not replace but updates a dst list

### ISSUE THREAD

**Issue by gerasym** [akesterson/dpath-python#69]
`from dpath.util import merge, MERGE_REPLACE

dict1 = {
    1: [1, 2, 3]
}
dict2 = {
    1: ['a']
}
merge(dict1, dict2, flags=MERGE_REPLACE)
print(dict1)`

return actual: {1: ['a', 2, 3]}
return expected: {1: ['a']}

Is it correct behavior? from documentation i read:
 MERGE_REPLACE : Instead of combining list objects, when
          2 list objects are at an equal depth of merge, replace
          the destination with the source.

**Comment by MaxBenChrist** [comment]
Any update on this? Is this intended behaviour?

Also, from glimpsing over the code, it looks like the MERGE_REPLACE flag is not used and thus not implemented, or am I missing something?

**Comment by akesterson** [comment]
This is not the intended behavior.

**Comment by akesterson** [comment]
You were correct, MERGE_REPLACE had never been implemented correctly. Fixed in pull #106.
