### ISSUE TITLE
Glob characters cannot be escaped

### ISSUE THREAD

**Issue by abarnert** [akesterson/dpath-python#80]
Python's `fnmatch` and `glob` don't allow escaping glob characters with a backslash.

This is by design for Python (even if it's a weird design), but I don't think it's what most people expect from `dpath`, even if they see the reference to `fnmatch`:

    >>> d = {'a': 23, '*': 42}
    >>> dpath.util.get(d, '*')
    ValueError: dpath.util.get() globs must match only one leaf : *
    >>> dpath.util.search(d, '*')
    {'a': 1, '*': 2}
    >>> dpath.util.get(d, r'\*')
    KeyError: '\\*'
    >>> dpath.util.search(d, r'\*')
    {}
    >>> dpath.util.get(d, '[*]') # is anyone going to guess this?
    42
    >>> dpath.util.search(d, '[*]')
    {'*': 42}

---

I've run into a similar issue in the past with many projects that want "globbing like the `glob` module but with backslash escapes". The simplest solution (but make sure to verify compatible licensing) is to fork `fnmatch` into your own code, and change this part of the `translate` function:

        if c == '*':

… to this:

        if c == '\\' and i < n:
            res = res + re.escape(pat[i])
            i = i+1
        elif c == '*':

However, that may not be all you need here.

I'm guessing (given the `KeyError`) that you have some code that checks for a wildcard and uses `fnmatch` if found but does a direct lookup if not. If so, your wildcard test has to change to understand backslashes (re.search on `(?<!\\)[*?[]`) and your direct-lookup has to manually unescape the same characters (re.sub on a similar pattern but that also handles `]` and `\\`). Although once you're getting into manually unescaping, you may want to consider what you want to do with a backslash before any other character—leave it as a backslash, unicode-unescape it, raise an exception, …

---

Fixing this could also make it easy to provide an alternate fix for #30 by allowing users to backslash-escape the path separator character.

**Comment by abarnert** [comment]
Another point: While glob characters can be escaped fnmatch-style by putting them inside a glob class, trying that for separators gives you something completely wrong and basically undebuggable:

    >>> d = {'a': {'b': 1}, 'a/b': 2, 'a[/]b': 3}
    >>> dpath.util.get(d, 'a[/]b')
    KeyError: 'a[/]b'

Also, I'm not sure what happens if you put `[**]` in a pattern—that _should_ do the same thing as `[*]`, and match a single literal `*`, but I wouldn't be surprised if your existing code treated it as a recursive glob.

**Comment by akesterson** [comment]
Your summary of the behavior of fnmatch/glob and our current use of it is correct. We haven't heard many users requesting the ability to escape glob characters, so we're not able to prioritize this currently.

For the 1.0 interface, check out the dpath.path module, the 'match' method. If you want to perform some amount of escaping on globs, this is where it would happen. I'd be happy to review a PR to that end.

**Comment by calebcase** [comment]
Use `[*][*]` to escape `**`.

**Comment by akesterson** [comment]
[This can be fixed by using lists as paths instead of strings](https://github.com/akesterson/dpath-python/blob/master/README.rst#separator-got-you-down-use-lists-as-paths)

> Separator got you down? Use lists as paths
> ==========================
> The default behavior in dpath is to assume that the path given is a string, which must be tokenized by splitting at the separator to yield a distinct set of path components against which dictionary keys can be individually glob tested. However, this presents a problem when you want to use paths that have a separator in their name; the tokenizer cannot properly understand what you mean by '/a/b/c' if it is possible for '/' to exist as a valid character in a key name.
> 
> To get around this, you can sidestep the whole "filesystem path" style, and abandon the separator entirely, by using lists as paths. All of the methods in dpath.util.* support the use of a list instead of a string as a path.
