### ISSUE TITLE
IndexError when deleting from lists

### ISSUE THREAD

**Issue by RcSepp** [akesterson/dpath-python#81]
Problem:
When deleting multiple values from lists using `dpath.util.delete(...)` the line `cur = cur[item[0]]` throws an index error, because indices of subsequent paths aren't adjusted when a previous path deletion modified the list.

Simple solution:
Remove paths in inverse order, by inserting `paths.reverse()` at line 62 of util.py.

Have a nice day,
RcSepp

**Comment by akesterson** [comment]
This behavior was merged some time ago. Please try with the latest version and let us know if this persists.
