### ISSUE TITLE
Allow the negation of globs to return all entries *not* matching

### ISSUE THREAD

**Issue by exhuma** [akesterson/dpath-python#86]
I'm currently looking for a good way to extract items from a complex dictionary which *don't* have certain keys set. `dpath` is really convenient to use to get matching items. But negating the search is either not possible or not documented.

**Comment by akesterson** [comment]
This would be a neat feature. We don't have the time to implement this currently, but leaving it open as an enhancement.

**Comment by akesterson** [comment]
This appears to have been resolved by the above commit ^ and the inverse_view method

Closing, please reopen if your need is not met
