### ISSUE TITLE
option to treat integer as list indices instead of dict keys in dpath.util.new

### ISSUE THREAD

**Issue by martinResearch** [akesterson/dpath-python#91]
at the moement whe we do 
  a={}
  dpath.util.new(a, 'b/2', 5)
we get  {'b': {'2': 5}}
while i would like to get {'b': [None, None, 5]}
a solution is to do 
dpath.util.new(a, 'b', [])
dpath.util.new(a, 'b/2', 5)

but adding this line migh not be becomes unpractical when there are several nested lists.

It would be good to have the possibility to tread integers as list indices by default and create theses lists in  dpath.util.new. That could be enabled by setting an option in dpath.options or as an option to dpath.util.new

**Comment by akesterson** [comment]
This is handled by the functionality in #101. The methodology is a little bit arcane - see the updated help message for dpath.path.set() and the example test added in that PR to see how this can be done.
